import type { SeriesConfig } from "../types";

/**
 * The fourteen configurations the PROS chassis produces, in size-chart order.
 *
 * Renders are the studio photography from `PROS.pdf`, extracted per page and cropped —
 * several configurations legitimately share one shot where the PDF only photographs the
 * family once.
 *
 * Some part codes are pattern-matched rather than read off the PDF; they are listed once
 * in the series' `inferredCodes` instead of being flagged here, so there is a single
 * place to fix when the real SKUs land.
 */
export const PROS_CONFIGS: SeriesConfig[] = [
  {
    slug: "single-short",
    n: "01",
    short: "Single 800",
    name: "Single Table · Short Beam",
    code: "PROS-ST-SB110",
    image: "/pros/single-desk.jpg",
    imageAlt: "PROS single table with modesty panel",
    finish: "oak",
    lens: [800, 1000],
    deps: [600, 700, 750],
    seats: "1",
    beam: "SB110",
    bom: [
      { name: "Short beam", code: "PRO-SB110-PC", qty: "1 pc" },
      { name: "Four-leg package", code: "PROS-4FLEG072-PC", qty: "1 pc" },
    ],
  },
  {
    slug: "single-medium",
    n: "02",
    short: "Single 1600",
    name: "Single Table · Medium Beam",
    code: "PROS-ST-SB160",
    image: "/pros/single-desk.jpg",
    imageAlt: "PROS single table with modesty panel",
    finish: "oak",
    lens: [1200, 1400, 1500, 1600],
    deps: [600, 700, 750, 900],
    seats: "1",
    beam: "SB160",
    bom: [
      { name: "Medium beam", code: "PRO-SB160-PC", qty: "1 pc" },
      { name: "Four-leg package", code: "PROS-4FLEG072-PC", qty: "1 pc" },
    ],
  },
  {
    slug: "return",
    n: "03",
    short: "Return",
    name: "Return Table",
    code: "PROS-RT-SB110",
    image: "/pros/return-desk.jpg",
    imageAlt: "PROS return table with desk screen",
    finish: "oak",
    lens: [1200, 1400, 1500, 1600],
    deps: [600, 700, 750],
    seats: "1",
    beam: "SB110",
    bom: [
      { name: "Two-leg package", code: "PROS-2FLEG072-PC", qty: "1 pc" },
      { name: "Four-leg package", code: "PROS-4FLEG072-PC", qty: "1 pc" },
      { name: "Short beam", code: "PRO-SB110-PC", qty: "1 pc" },
    ],
  },
  {
    slug: "bench-2",
    n: "04",
    short: "2 Seater",
    name: "Bench · 2 Seaters",
    code: "PROS-BN2-SB160",
    image: "/pros/bench-2.jpg",
    imageAlt: "PROS two-seater bench with screens",
    finish: "oak",
    lens: [1200, 1400, 1500, 1600],
    deps: [600, 700, 750, 900],
    seats: "2",
    beam: "SB160",
    bom: [
      { name: "Medium beam", code: "PRO-SB160-PC", qty: "1 pc" },
      { name: "Bench legs, one pair", code: "PROS-2BLEG-PC", qty: "1 pc" },
      { name: "Bench mid leg", code: "PROS-BMLEG-PC", qty: "2 pcs" },
    ],
  },
  {
    slug: "bench-4",
    n: "05",
    short: "4 Seater",
    name: "Bench · 4 Seaters with Screen",
    code: "PROS-BN4-SB160",
    image: "/pros/bench-4-screen.jpg",
    imageAlt: "PROS four-seater bench with side screens",
    finish: "oak",
    lens: [1200, 1400, 1500, 1600],
    deps: [600, 700, 750, 900],
    seats: "4",
    beam: "SB160",
    bom: [
      { name: "Medium beam", code: "PRO-SB160-PC", qty: "2 pcs" },
      { name: "Bench legs, one pair", code: "PROS-2BLEG-PC", qty: "1 pc" },
      { name: "Bench mid leg", code: "PROS-BMLEG-PC", qty: "4 pcs" },
    ],
  },
  {
    slug: "bench-4-front",
    n: "06",
    short: "4 Inline",
    name: "Bench · 4 Seaters, Inline",
    code: "PROS-BN4-SB200",
    image: "/pros/bench-4-screen.jpg",
    imageAlt: "PROS four-seater bench, inline run with screens",
    finish: "oak",
    lens: [1600, 1800, 2000],
    deps: [600, 700, 750, 900],
    seats: "4",
    beam: "SB200",
    bom: [
      { name: "Long beam", code: "PRO-SB200-PC", qty: "2 pcs" },
      { name: "Bench legs, one pair", code: "PROS-2BLEG-PC", qty: "2 pcs" },
      { name: "Bench mid leg", code: "PROS-BMLEG-PC", qty: "4 pcs" },
    ],
  },
  {
    slug: "l-shape",
    n: "07",
    short: "L Shape",
    name: "L Shape Table",
    code: "PROS-LS-SB160",
    image: "/pros/l-shape.jpg",
    imageAlt: "PROS L-shape table in Espresso Walnut",
    finish: "walnut",
    lens: [1500, 1600, 1800],
    deps: [600, 700, 750, 900],
    seats: "1",
    beam: "SB160",
    bom: [
      { name: "Medium beam", code: "PRO-SB160-PC", qty: "1 pc" },
      { name: "Four-leg package", code: "PROS-4FLEG072-PC", qty: "1 pc" },
      { name: "Two-leg package", code: "PROS-2FLEG072-PC", qty: "1 pc" },
      { name: "Straight connector", code: "PROS-SCON-PC", qty: "1 pc" },
    ],
  },
  {
    slug: "manager",
    n: "08",
    short: "Manager",
    name: "Manager Table with Cabinet",
    code: "PROS-MT-SB200",
    image: "/pros/manager-cabinet.jpg",
    imageAlt: "PROS manager table with side cabinet",
    finish: "walnut",
    lens: [1600, 1800, 2000],
    deps: [750, 900],
    seats: "1",
    beam: "SB200",
    bom: [
      { name: "Long beam", code: "PRO-SB200-PC", qty: "1 pc" },
      { name: "Four-leg package", code: "PROS-4FLEG072-PC", qty: "1 pc" },
      { name: "Side cabinet", code: "PROS-SCAB-1200", qty: "1 pc" },
    ],
  },
  {
    slug: "u-shape",
    n: "09",
    short: "U Shape",
    name: "U Shape Table",
    code: "PROS-US-SB200",
    image: "/pros/u-shape.jpg",
    imageAlt: "PROS U-shape table in Espresso Walnut",
    finish: "walnut",
    lens: [1800, 2000],
    deps: [750, 900],
    seats: "1",
    beam: "SB200",
    bom: [
      { name: "Long beam", code: "PRO-SB200-PC", qty: "1 pc" },
      { name: "Four-leg package", code: "PROS-4FLEG072-PC", qty: "1 pc" },
      { name: "Two-leg package", code: "PROS-2FLEG072-PC", qty: "2 pcs" },
      { name: "Straight connector", code: "PROS-SCON-PC", qty: "2 pcs" },
    ],
  },
  {
    slug: "exec",
    n: "10",
    short: "Executive",
    name: "Executive Suite",
    code: "PROS-EX-SB200",
    image: "/pros/exec-suite.jpg",
    imageAlt: "PROS executive suite with credenza and side cabinet",
    finish: "walnut",
    lens: [1800, 2000],
    deps: [900],
    seats: "1",
    beam: "SB200",
    bom: [
      { name: "Long beam", code: "PRO-SB200-PC", qty: "1 pc" },
      { name: "Four-leg package", code: "PROS-4FLEG072-PC", qty: "1 pc" },
      { name: "Credenza", code: "PROS-CRED-1600", qty: "1 pc" },
      { name: "Side cabinet", code: "PROS-SCAB-1200", qty: "1 pc" },
    ],
  },
  {
    slug: "meet-square",
    n: "11",
    short: "Sq Meeting",
    name: "Small Meeting · Square",
    code: "PROS-MSQ",
    image: "/pros/meet-square.jpg",
    imageAlt: "PROS square meeting table for four",
    finish: "walnut",
    lens: [800, 1000],
    deps: [800, 1000],
    seats: "4",
    beam: "—",
    sq: true,
    bom: [{ name: "Two-leg package", code: "PROS-2FLEG072-PC", qty: "2 pcs" }],
  },
  {
    slug: "meet-round",
    n: "12",
    short: "Rd Meeting",
    name: "Small Meeting · Round",
    code: "PROS-MRD",
    image: "/pros/meet-round.jpg",
    imageAlt: "PROS round meeting table for four",
    finish: "walnut",
    lens: [800, 900, 1000, 1200],
    deps: [800, 900, 1000, 1200],
    seats: "4",
    beam: "—",
    dia: true,
    bom: [{ name: "Two-leg package", code: "PROS-2FLEG072-PC", qty: "2 pcs" }],
  },
  {
    slug: "meet-rect",
    n: "13",
    short: "Meeting 2m",
    name: "Meeting Table · Medium Beam",
    code: "PROS-MT-SB160",
    image: "/pros/meet-rect.jpg",
    imageAlt: "PROS rectangular meeting table for six",
    finish: "walnut",
    lens: [1600, 1800, 2000],
    deps: [600, 700, 750],
    seats: "6",
    beam: "SB160",
    bom: [
      { name: "Medium beam", code: "PRO-SB160-PC", qty: "1 pc" },
      { name: "Bench legs, one pair", code: "PROS-2BLEG-PC", qty: "1 pc" },
      { name: "Bench mid leg", code: "PROS-BMLEG-PC", qty: "2 pcs" },
    ],
  },
  {
    slug: "meet-long",
    n: "14",
    short: "Boardroom",
    name: "Meeting Table · Long Beam",
    code: "PROS-MT-SB200",
    image: "/pros/meet-long.jpg",
    imageAlt: "PROS boardroom table on the long beam",
    finish: "walnut",
    lens: [2400, 3200, 3600, 4000],
    deps: [1200],
    seats: "8–12",
    beam: "SB200",
    bom: [
      { name: "Long beam", code: "PRO-SB200-PC", qty: "1 pc" },
      { name: "Bench legs, one pair", code: "PROS-2BLEG-PC", qty: "1 pc" },
      { name: "Bench mid leg", code: "PROS-BMLEG-PC", qty: "2 pcs" },
      { name: "Wire box", code: "PROS-WBOX-PC", qty: "2 pcs" },
    ],
  },
];

/** Landing configuration — the boardroom table shows the range's reach. */
export const PROS_DEFAULT_SLUG = "meet-long";
